### ISSUE TITLE
Broken with symfony 7.1

### ISSUE THREAD

**Issue by faizanakram99** [api-platform/core#6411]
**API Platform version(s) affected**: x.y.z

**Description**  
With symfony 7.1 I get this error when i try lint:container command

Invalid alias definition: alias "ApiPlatform\Serializer\SerializerContextBuilderInterface" is referencing class "ApiPlatform\OpenApi\Serializer\SerializerContextBuilder" but this class does not implement "ApiPlatform\Serializer\SerializerContextBuilderInterface". Because this alias is an interface,    "ApiPlatform\OpenApi\Serializer\SerializerContextBuilder" must implement "ApiPlatform\Serializer\SerializerContextBuilderInterface".   

**How to reproduce**  
Upgrade to symfony 7.1

**Possible Solution**  
"ApiPlatform\OpenApi\Serializer\SerializerContextBuilder" should implement "ApiPlatform\Serializer\SerializerContextBuilderInterface"

**Additional Context**

**Comment by faizanakram99** [comment]
This is the offending commit https://github.com/api-platform/core/commit/732d4aa8c32e6b3ec01a713b032a2c01adf66e5d

**Comment by soyuka** [comment]
98e9cace0646052b08b7142d74c89a7ed0f32b6a fixes that
